#config_version=6

# fast:
#   net:
#     port: auto
#     controller: neuron
#     io_loop:
#       3208:
#         model: FP-I/O-3208
#         order: 1
#   exp:
#     port: auto
#     boards:
#       neuron:
#         model: FP-EXP-2000
